algoritmo "PRATICA - AULA 14.1"
var
   N: vetor[1..5] de inteiro
   C: Inteiro
inicio
   Para C <- 1 ate 5 faça
      Escreva ("Digite o", C, "º número:")
      Leia (N[C])
   FimPara

   Para C <- 5 ate 1 passo -1 faça
      Escreval (N[C])
   FimPara

   Escreval("-------------------------")

   Para C <- 1 ate 5 faça
      Escreva ("Digite o", C, "º número:")
      Leia (N[C])
   FimPara

   Para C <- 1 ate 5 faça
      Escreval (N[C])
   FimPara
fimalgoritmo