algoritmo "semnome"
var
Ing: logico
ID: inteiro
Nome: caracter
PEntrar: logico
inicio
Escreval ("Boa noite, qual é seu nome:")
Leia (Nome)
Escreval ("Seja muito Bem-Vindo, ", Nome, "!")
EscrevaL ("Qual sua idade:")
Leia (ID)
Escreval ("Pela análise do sistema se der verdadeiro, você pode entrar, caso contrário não!", PEntrar)
ID <- 18
Ing <- Verdadeiro
PEntrar <- (ID >= 18) e (Ing)
fimalgoritmo